coscyrix/mindbridge

- server/controllers/form.js
- server/models/common.js
- server/models/form.js
- server/models/session.js
- server/models/thrpyReq.js
- server/routes/form.js
- server/routes/index.js
- server/server.js
- server/services/form.js
- server/utils/emailTmplt.js
This pull request introduces several new functionalities and improvements across various files in the server-side codebase. The changes mainly focus on adding form handling capabilities, enhancing session management, and improving error handling and logging.
* [`server/controllers/form.js`](diffhunk://#diff-ae5bc598b661ad36bf136a62db5702aada09cbe4cc33ca67bd2eece1febba699R1-R49): Added a new `FormController` class with methods to handle POST, PUT, and GET requests for forms.
* [`server/models/form.js`](diffhunk://#diff-e6ef8b51e6a750f13ad2e77b5160b3de4d6a45b1876c2c025a9d8a1903944b5bR1-R264): Introduced a new `Form` class to manage form-related database operations, including validation and insertion of form data.
* [`server/routes/form.js`](diffhunk://#diff-9be4540481950cfcf298b9d346765d3322 …
> Add form handling routes, controller, and service; implement treatment

- server/models/session.js
- server/models/thrpyReq.js
- server/package-lock.json
- server/package.json
- server/server.js
This pull request includes several updates to the `Session` and `ThrpyReq` classes, the addition of a new cron job for daily session status updates, and the inclusion of new dependencies in the project.
* Commented out unused fields in the `Session` class (`session_description`, `is_additional`, `is_report`).
* Added a new method `getSessionByThrpyReqId` to fetch sessions by therapy request ID.
* Added a new method `dailyUpdateSessionStatus` to update session statuses daily.
* Enhanced `delThrpyReqById` method to check for existing therapy requests and related sessions before deletion. [[1]](diffhunk://#diff-8c96712eadb5e86f93b95b7fb95fecfe18eb36b1fe521d730675f882ce95beadR406-R439) [[2]](diffhunk://#diff-8c96712eadb5e86f93b95b7fb95fecfe18eb36b1fe521d730675f882ce95beadR449-R465)
* Added …
> Implement daily session status update and add therapy request deletion session-nov24

- server/config/server.config.js
- server/controllers/form.js
- server/controllers/invoice.js
- server/controllers/service.js
- server/controllers/session.js
- server/controllers/thrpyReq.js
- server/controllers/user.js
- server/controllers/userProfile.js
- server/services/form.js
- server/services/invoice.js
- server/services/service.js
- server/services/session.js
- server/services/thrpyReq.js
- server/services/user.js
- server/services/userProfile.js
This pull request includes several changes to improve error handling and add HTTPS support to the server configuration. The most important changes are grouped into two themes: adding HTTPS support and improving error handling in controllers and services.
* [`server/config/server.config.js`](diffhunk://#diff-3b646fa18c86c15c894ef010dcd208a28e010898f21e6e86188f700b24ce2adfR8): Added the `https` module and created an HTTPS server configuration for production environments, using SSL certificates from environment variables. [[1]](diffhunk://#diff-3b646fa18c86c15c894ef010dcd208a28e010898f21e6e86188f700b24ce2adfR8) [[2]](diffhunk://#diff-3b646fa18c86c15c894ef010dcd208a28e010898f21e6e86188f700b24ce2adfR104-R118)
* [`server/controllers/form.js`](diffhunk://#diff-ae5bc598b661ad36bf136a62db5702aada09 …
> Enhance error handling in form, invoice, session, and service service…s and controllers

- server/controllers/references.js
- server/controllers/userTargetOutcome.js
- server/models/reference.js
- server/models/service.js
- server/models/userProfile.js
- server/models/userTargetOutcome.js
- server/routes/index.js
- server/routes/references.js
- server/routes/userTargetOutcome.js
- server/server.js
- server/services/references.js
- server/services/service.js
- server/services/userProfile.js
- server/services/userTargetOutcome.js
This pull request introduces several new features and improvements to the codebase, primarily focusing on handling references and user target outcomes. The most important changes include the addition of new controllers, services, models, and routes for managing references and user target outcomes, as well as updates to the existing service model.
* **References Management:**
* Added `ReferencesController` with a `getReferences` method to handle fetching references.
* Created `ReferencesService` to interact with the `Reference` model and fetch reference data.
* Implemented `Reference` model to interact with the database and fetch various reference data.
* Added `referencesRouter` to define the API endpoint for fetching references.
* **User Target Outcome Management:**
* Added …
> Add references and user target outcome routes, controllers, and services

- server/config/server.config.js
- server/controllers/userProfile.js
- server/models/auth/user.js
- server/routes/user.js
This pull request includes several changes to the server configuration, user profile controller, and user model to improve error handling and update environment settings. The most important changes include modifying environment settings in the server configuration, commenting out validation checks in the user profile controller, and enhancing error messages in the user model.
* Updated environment setting from 'development' to 'local_dev' and added additional server creation logic based on the 'development' environment in `server/config/server.config.js`.
* Commented out the validation check for query parameters in the `getUserProfileById` method in `server/controllers/userProfile.js`.
* Added error codes to various error messages in the `User` class methods in …
> Refactor server configuration and user profile error handling; rename reset-password route to forgot-password

- server/models/userProfile.js
- server/services/userProfile.js
This pull request includes several changes to the `UserProfile` class and the `UserProfileService` class to improve the handling of user profile updates and validation.
Improvements to user profile updates:
* [`server/models/userProfile.js`](diffhunk://#diff-b219d37d89121c3978780890f2d05aafaf7f9241865a3aa79b7b3ec09185e997L167-R171): Modified the `putUserProfile` method to use conditional object properties for updating user profile fields, ensuring only provided fields are updated.
* [`server/models/userProfile.js`](diffhunk://#diff-b219d37d89121c3978780890f2d05aafaf7f9241865a3aa79b7b3ec09185e997L185-R195): Updated the logic to handle optional `email` and `role_id` fields when updating user profiles, including a new check for `role_id`.
Enhancements to user profile validation:
* …
> Refactor user profile update logic to conditionally include fields; add role_id validation

- server/config/server.config.js
This pull request includes changes to the `server/config/server.config.js` file to update the server configuration logic based on the environment. The most important changes include modifying the environment variable checks and the creation of the HTTP/HTTPS server.
Changes to server configuration:
* [`server/config/server.config.js`](diffhunk://#diff-3b646fa18c86c15c894ef010dcd208a28e010898f21e6e86188f700b24ce2adfL116-R123): Updated the environment variable check from `development` to `local_development` for creating the HTTP server. Additionally, added a new condition to create an HTTPS server for the `development` environment.
> Update server configuration to conditionally create HTTP/HTTPS server based on environment

- server/models/thrpyReq.js
- server/services/thrpyReq.js
This pull request includes several significant updates to the `ThrpyReq` class in `server/models/thrpyReq.js` and the `ThrpyReqService` class in `server/services/thrpyReq.js`. The changes primarily focus on improving error handling, adding new fields for therapy request updates, and ensuring proper validation of input data.
Error handling and validation improvements:
* Added error handling and validation for checking therapy requests before updating them, including logging errors and returning appropriate messages when requests are not found or errors occur.
* Included validation for new optional fields `status_yn` and `thrpy_status` in the `ThrpyReqService` class using Joi schema validation. [[1]](diffhunk://#diff-5d48dccb6f255f17c19b0422ca4015112bb852682fe9eb04af535403d99e248dR40-R41) …
> Enhance ThrpyReq model and service with error handling and optional fields for status management

- server/models/form.js
- server/models/thrpyReq.js
This pull request includes significant updates to the `ThrpyReq` class in `server/models/thrpyReq.js` to enhance functionality and error handling. Additionally, a small change was made to the `Form` class in `server/models/form.js` to improve error handling.
Enhancements in `ThrpyReq` class:
* Added checks to prevent requesting additional or report services.
* Implemented a check to ensure the intake date is not in the past.
* Introduced a method `checkThrpyReqActive` to verify if the client has an active therapy request with the same service and counselor.
Error handling improvements:
* Simplified the condition to check for empty records in the `Form` class.
* Added error handling for loading session forms and updating session forms in the `ThrpyReq` class.
These changes aim to improve …
> Add validation for therapy requests and enhance error handling

- server/controllers/session.js
- server/controllers/thrpyReq.js
- server/models/common.js
- server/models/session.js
- server/models/thrpyReq.js
- server/models/userProfile.js
- server/routes/session.js
- server/services/session.js
- server/utils/emailTmplt.js
This pull request includes several changes to the backend controllers, models, and services to enhance functionality and improve error handling. The most important changes include adding new methods to handle specific tasks, modifying existing methods to include additional checks and logging, and cleaning up unused code.
* Added a check to ensure a note is provided when the session status is 3 (NO SHOW) in `SessionController` (`server/controllers/session.js`).
* Introduced a new method `getSessionTodayAndTomorrow` in `SessionController` to retrieve sessions for today and tomorrow (`server/controllers/session.js`).
* Added validation and a new method `getSessionTodayAndTomorrow` in `SessionService` to support the new functionality in `SessionController` (`server/services/session.js`).
* …
> Add endpoints for retrieving sessions and enhance session validation

- server/models/session.js
This pull request includes changes to the `Session` class in the `server/models/session.js` file to improve the handling of session data and streamline the code. The most important changes include the use of conditional object properties, removal of redundant code, and fixing a method call.
Improvements to session data handling:
* [`server/models/session.js`](diffhunk://#diff-bb67af2f02247a1d8d2d180db446072d4b2320335a05fa89de094a533e1a123bL148-R165): Used conditional object properties to include only defined session data fields, making the code more concise and readable.
Codebase simplification:
* [`server/models/session.js`](diffhunk://#diff-bb67af2f02247a1d8d2d180db446072d4b2320335a05fa89de094a533e1a123bL148-R165): Removed redundant code that duplicated session data handling logic, …
> Refactor session model to streamline session status handling and improve conditional logic

- server/controllers/thrpyReq.js
- server/models/session.js
- server/models/thrpyReq.js
- server/models/userProfile.js
- server/routes/thrpyReq.js
- server/services/thrpyReq.js
- server/services/userProfile.js
- server/utils/emailTmplt.js
This pull request includes several changes to the therapy request and session management functionality. The most important changes are the addition of new methods to handle therapy requests and sessions, as well as the integration of email notifications for various actions.
* [`server/controllers/thrpyReq.js`](diffhunk://#diff-c4a656ccbb997a28df155e3285674cd10ec4c3206df05f8024b728d8eb0a87aaR55-R77): Added a new method `putThrpyBigObjReqById` to handle updating therapy requests with large objects.
* [`server/models/session.js`](diffhunk://#diff-bb67af2f02247a1d8d2d180db446072d4b2320335a05fa89de094a533e1a123bR110-R118): Added methods `checkSessionONGOING` and `putSessionById` to check if a session is ongoing and to update a session by ID, respectively. …
> Add endpoint for updating large therapy requests and enhance user profile validation

- server/controllers/session.js
- server/models/common.js
- server/models/emailTmplt.js
- server/models/session.js
- server/models/thrpyReq.js
- server/models/userProfile.js
- server/services/session.js
This pull request includes significant changes to the email handling and session retrieval functionalities in the application. The main changes involve the refactoring of email sending logic into a new `EmailTmplt` class and updates to the session retrieval methods.
* Introduced a new `EmailTmplt` class in `server/models/emailTmplt.js` to centralize email sending logic, including methods for sending various types of emails such as treatment tools, discharge, therapy request details, welcome client, and consent form emails.
* Updated `Session`, `ThrpyReq`, and `UserProfile` classes to use the new `EmailTmplt` class for sending emails, replacing the previous inline email sending logic. [[1]](diffhunk://#diff-bb67af2f02247a1d8d2d180db446072d4b2320335a05fa89de094a533e1a123bR22) …
> Enhance session handling by adding optional session_status field and refactor getSessionById method to accept query parameters

- server/controllers/userProfile.js
- server/models/invoice.js
- server/models/userProfile.js
- server/services/invoice.js
- server/services/userProfile.js
This pull request includes several changes to the `server` directory, focusing on improving validation, updating date handling, and enhancing user profile creation logic. The most important changes are summarized below:
* Added validation checks for `role_id` and `target_outcome_id` in `userPostClientProfile` method in `UserProfileController` to ensure required fields are provided based on the role.
* Updated `Invoice` model to handle date range queries using `start_dte` and `end_dte` instead of `req_dte`. [[1]](diffhunk://#diff-0fe13c928d34649aa0b09f3731c977983b398178a328c34b4b4c79ddc4f0be80L151-R156) [[2]](diffhunk://#diff-0fe13c928d34649aa0b09f3731c977983b398178a328c34b4b4c79ddc4f0be80L165-R195)
* Modified `InvoiceService` to validate `start_dte` and `end_dte` instead of `req_dte`.
* …
> Enhance user profile validation and invoice summary calculation; update role-based requirements and optional fields

- server/controllers/feedback.js
- server/controllers/invoice.js
- server/models/emailTmplt.js
- server/models/feedback.js
- server/models/reference.js
- server/models/session.js
- server/routes/feedback.js
- server/routes/index.js
- server/server.js
- server/services/feedback.js
- server/services/invoice.js
- server/services/session.js
- server/utils/emailTmplt.js
This pull request introduces a new feedback system, adds validation for certain fields in the invoice controller, and includes several enhancements to session handling. The most important changes include the creation of a feedback controller with various feedback methods, the addition of validation in the invoice controller, and the integration of feedback routes into the server.
* [`server/controllers/feedback.js`](diffhunk://#diff-092a63d3540a8419a1895bb5da41efc2180c0a233d2889014b6a2d350ea974c6R1-R127): Created `FeedbackController` with methods for posting, updating, and retrieving feedback, as well as specific methods for GAD7, PHQ9, WHODAS, and IPF feedback.
* [`server/services/feedback.js`](diffhunk://#diff-4482e14aba6c903d9f2cb4bc4ce534d2817ef5653303fa6d4434b806b3d2cbacR1-R268): …
> Add feedback routes and controller; enhance invoice and session validation

- server/controllers/feedback.js
- server/models/emailTmplt.js
- server/models/feedback.js
- server/models/userProfile.js
- server/routes/feedback.js
- server/services/feedback.js
- server/utils/emailTmplt.js
This pull request introduces several new feedback routes and corresponding methods in the `FeedbackController`, as well as updates to the feedback model and service to accommodate these new routes. The changes also include modifications to the email template and user profile models.
* Added `postPCL5Feedback`, `postSMARTGOALFeedback`, and `postCONSENTFeedback` methods to `FeedbackController` to handle new types of feedback submissions. [[1]](diffhunk://#diff-092a63d3540a8419a1895bb5da41efc2180c0a233d2889014b6a2d350ea974c6R98-R113) [[2]](diffhunk://#diff-092a63d3540a8419a1895bb5da41efc2180c0a233d2889014b6a2d350ea974c6R143-R174)
* Updated `feedback.js` routes to include new endpoints for PCL5, SMART GOAL, and CONSENT feedback submissions. …
> Add new feedback endpoints and enhance email templates; update validation for client ID and session ID

- server/#Environment Configuration.env
- server/controllers/notes.js
- server/models/invoice.js
- server/models/notes.js
- server/models/thrpyReq.js
- server/routes/index.js
- server/routes/notes.js
- server/server.js
- server/services/notes.js
This pull request introduces several new features and improvements, including the addition of a new `Notes` functionality, configuration updates, and minor adjustments in existing models.
* **Notes Functionality:**
- Added `NotesController` with methods to handle posting, updating, and retrieving notes. (`server/controllers/notes.js`)
- Created `Notes` model to interact with the database for note-related operations. (`server/models/notes.js`)
- Implemented `NotesService` to validate and process note data before interacting with the `Notes` model. (`server/services/notes.js`)
- Added routes for the new notes functionality, including POST, PUT, and GET endpoints. (`server/routes/notes.js`, `server/routes/index.js`, `server/server.js`) …
> Add notes functionality with CRUD operations and environment configuration

- server/models/invoice.js
- server/models/session.js
- server/models/thrpyReq.js
This pull request includes several changes to the `server/models/invoice.js`, `server/models/session.js`, and `server/models/thrpyReq.js` files to improve invoice handling and session management. The most important changes include adding checks for existing invoices, improving error handling, and removing commented-out code.
* Added checks to ensure that the invoice number and session ID are unique before creating a new invoice in `postInvoice` method. [[1]](diffhunk://#diff-0fe13c928d34649aa0b09f3731c977983b398178a328c34b4b4c79ddc4f0be80R13-L15) [[2]](diffhunk://#diff-0fe13c928d34649aa0b09f3731c977983b398178a328c34b4b4c79ddc4f0be80R27-R39)
* Implemented a new method `delInvoiceBySessionId` to delete an invoice by session ID, which is used to handle cases where an invoice needs to be …
> Add invoice number validation and deletion logic; refactor session invoicing checks

- server/models/thrpyReq.js
- server/services/userProfile.js
This pull request includes changes to the `server/models/thrpyReq.js` and `server/services/userProfile.js` files to improve data handling and validation. The most important changes are as follows:
Data handling improvements in `ThrpyReq` class:
* Added a filter to remove sessions where `is_report` equals 1 from `session_obj`.
* Sorted `session_obj` by `session_id` to ensure sessions are in the correct order.
Validation improvements in `UserProfileService` class:
* Added validation for `user_phone_nbr` to ensure it is an optional integer between 10 and 15 digits.
> Filter out reported sessions and sort session objects; add optional user phone number validation

- server/models/userProfile.js
This pull request introduces a new method to the `UserProfile` class in `server/models/userProfile.js` to check if a client or counselor has an active schedule. The most important changes include adding the new method `checkClientOrCounselorHasActiveSchedule` and updating the existing code to utilize this new method.
New method addition:
* [`server/models/userProfile.js`](diffhunk://#diff-b219d37d89121c3978780890f2d05aafaf7f9241865a3aa79b7b3ec09185e997R436-R463): Added the `checkClientOrCounselorHasActiveSchedule` method to check if a user has an active schedule by querying the database.
Code update to use the new method:
* [`server/models/userProfile.js`](diffhunk://#diff-b219d37d89121c3978780890f2d05aafaf7f9241865a3aa79b7b3ec09185e997R230-R241): Updated the existing code to call the new …
> Add active schedule check for clients and counselors in user profile

- server/controllers/session.js
- server/models/common.js
- server/models/session.js
- server/services/session.js
This pull request includes multiple changes to enhance session management by adding role and user profile checks. The changes primarily focus on updating the session controller, model, and service to handle new fields and validation logic.
* [`server/controllers/session.js`](diffhunk://#diff-2cef655d135c56b66f67da70f01571cdf9f9a4b80ab1f7c504f129b9896d066fL33-R40): Updated `putSessionById` method to include `role_id` and `user_profile_id` in the request handling and added validation to check for mandatory fields. [[1]](diffhunk://#diff-2cef655d135c56b66f67da70f01571cdf9f9a4b80ab1f7c504f129b9896d066fL33-R40) [[2]](diffhunk://#diff-2cef655d135c56b66f67da70f01571cdf9f9a4b80ab1f7c504f129b9896d066fR53-R60)
* [`server/models/common.js`](diffhunk://#diff-0c3bc2e8f4de98e70756d10fd62389b38b36e97c0bd …
> Add user role validation and session access checks in session management

- server/models/thrpyReq.js
- server/models/userProfile.js
This pull request includes several important changes to the `server/models/thrpyReq.js` and `server/models/userProfile.js` files, focusing on role validation and email handling improvements. The most significant updates are the addition of role checks for counselors and clients, and the conditional sending of client consent emails.
Role validation improvements in `server/models/thrpyReq.js`:
* Added checks to ensure that the specified counselor has the correct role (`role_id` of 2) and return an error message if not.
* Added checks to ensure that the specified client has the correct role (`role_id` of 1) and return an error message if not.
Email handling improvements in `server/models/userProfile.js`:
* Added a condition to send the client consent email only if the user's role is a client …
> Add role validation for counselors and clients in therapy request processing

- server/models/auth/user.js
- server/utils/emailTmplt.js
This pull request includes changes to the `server/models/auth/user.js` and `server/utils/emailTmplt.js` files to enhance account status handling and improve email notifications. The most important changes include adding a new email template for account verification, modifying the user model to handle account deactivation and verification more effectively, and updating email sending logic.
Enhancements to account status handling:
* [`server/models/auth/user.js`](diffhunk://#diff-33db7a3e16304801a16a14e4d20c583b3e1fa6596a23c41810e337bd04dd2450L87-R125): Added logic to check if an account is verified and send an account verification email if it is not. Updated the existing logic to handle account deactivation more effectively, including sending an account deactivated email and improving …
> Add account verification email template and enhance account status checks

- server/models/emailTmplt.js
- server/models/feedback.js
- server/models/session.js
- server/models/thrpyReq.js
This pull request includes several changes to the email template and therapy request functionality in the `server/models` directory. The most important changes include fixing method names, updating the way user profiles are accessed, and removing commented-out code.
* Corrected the method name from `sendTreatmetToolEmail` to `sendTreatmentToolEmail` in `EmailTmplt` and updated its usage in `Session` (`server/models/emailTmplt.js`, `server/models/session.js`) [[1]](diffhunk://#diff-f867a80f78decb0f945a5e9973d614903ab9342beb6a04bc601b982f503303e6L29-R29) [[2]](diffhunk://#diff-bb67af2f02247a1d8d2d180db446072d4b2320335a05fa89de094a533e1a123bL201-R201).
* Simplified the `getUserProfileByUserProfileId` call in `sendDischargeEmail` to directly pass `data.client_id` and added a log statement for …
> Fix email template method name and clean up unused code in session and therapy request models

- server/models/common.js
- server/models/session.js
- server/models/thrpyReq.js
This pull request includes several changes to the `server/models` directory, focusing on error handling, session management, and therapy request checks. The most important changes are the addition of new methods for checking therapy request statuses, updates to session handling logic, and improvements to error logging.
* Added `console.log` and `logger.error` calls to improve error logging in `server/models/common.js` and `server/models/thrpyReq.js`. [[1]](diffhunk://#diff-0c3bc2e8f4de98e70756d10fd62389b38b36e97c0bdbc454b59116a1dbefaf28R262) [[2]](diffhunk://#diff-0c3bc2e8f4de98e70756d10fd62389b38b36e97c0bdbc454b59116a1dbefaf28L334-R379) [[3]](diffhunk://#diff-8c96712eadb5e86f93b95b7fb95fecfe18eb36b1fe521d730675f882ce95beadR867-L811)
* Added `session_code` to session creation and update …
> Add therapy request discharge check and enhance session update logic

- server/controllers/userForm.js
- server/models/session.js
- server/models/thrpyReq.js
- server/models/userForm.js
- server/routes/index.js
- server/routes/userForm.js
- server/server.js
- server/services/userForm.js
This pull request introduces a new feature for managing user forms, including the creation, updating, and retrieval of user forms. The changes span across multiple files, adding new routes, controllers, services, and models to support this functionality.
**New User Form Management Feature:**
* [`server/controllers/userForm.js`](diffhunk://#diff-d89ddb8d3e295892f1f3613b21dd346ba6f45a3b26c568bb58dfa1bf4a617f66R1-R64): Added `UserFormController` class with methods to handle POST, PUT, and GET requests for user forms.
* [`server/models/userForm.js`](diffhunk://#diff-5d67632e9da28347785c5ccbdb1e7a2e367b404c9cb012cbbf857ce904d8abfeR1-R132): Created `UserForm` class with methods to interact with the database for creating, updating, and retrieving user forms.
* …
> Add user form functionality with CRUD operations and integrate into routing

- server/controllers/userForm.js
- server/models/userForm.js
- server/routes/userForm.js
- server/services/userForm.js
This pull request includes several changes to the user form functionality, focusing on expanding the query parameters for retrieving user forms and making minor adjustments to routes and services.
* [`server/controllers/userForm.js`](diffhunk://#diff-d89ddb8d3e295892f1f3613b21dd346ba6f45a3b26c568bb58dfa1bf4a617f66L48-R57): Expanded the `getUserFormById` method to include additional query parameters such as `session_id`, `form_id`, `client_id`, `counselor_id`, `start_date`, and `end_date`.
* [`server/models/userForm.js`](diffhunk://#diff-5d67632e9da28347785c5ccbdb1e7a2e367b404c9cb012cbbf857ce904d8abfeR121-R132): Updated the query logic in the `UserForm` class to filter results based on the new query parameters, including `form_id`, `start_date`, and `end_date`.
* …
> Enhance user form retrieval by adding additional query parameters and updating validation schema
